language: bash

services: docker

script:
  - docker build -t andrewmclagan/aphex:"$TRAVIS_TAG" -t andrewmclagan/aphex:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push andrewmclagan/aphex:"$TRAVIS_TAG";
    docker push andrewmclagan/aphex:latest;
    fi
