language: bash

services: docker

env: 
  - REPO=andrewmclagan/aphex

before_script:
  - export REPO_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`   
  - export REPO_IMAGE="${REPO}:${REPO_TAG}"  
  - docker pull "$REPO"

script:
  - echo "${REPO_IMAGE}"
  - docker build -t "$REPO_IMAGE" .
  - docker images 

after_success:
  - echo "${REPO_IMAGE}"  
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push "$REPO_IMAGE"