language: bash

services: docker

env: 
  - REPO=andrewmclagan/aphex

before_script:
  - export REPO_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`   
  - image="${REPO}:${REPO_TAG}"  

script:
  - docker build -t "$image" .

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push "$image"